// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: engine/types/core/lango.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [Lang] stores information about mimik's supported language.
// i1 refers to ISO 639-1 code. i2, i3... refer to ISO 639-2, ISO 639-3, etc.
type Lang struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	I1            string                 `protobuf:"bytes,2,opt,name=i1,proto3" json:"i1,omitempty"`
	I2            string                 `protobuf:"bytes,3,opt,name=i2,proto3" json:"i2,omitempty"`
	I3            string                 `protobuf:"bytes,4,opt,name=i3,proto3" json:"i3,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lang) Reset() {
	*x = Lang{}
	mi := &file_engine_types_core_lango_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lang) ProtoMessage() {}

func (x *Lang) ProtoReflect() protoreflect.Message {
	mi := &file_engine_types_core_lango_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lang.ProtoReflect.Descriptor instead.
func (*Lang) Descriptor() ([]byte, []int) {
	return file_engine_types_core_lango_proto_rawDescGZIP(), []int{0}
}

func (x *Lang) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lang) GetI1() string {
	if x != nil {
		return x.I1
	}
	return ""
}

func (x *Lang) GetI2() string {
	if x != nil {
		return x.I2
	}
	return ""
}

func (x *Lang) GetI3() string {
	if x != nil {
		return x.I3
	}
	return ""
}

func (x *Lang) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_engine_types_core_lango_proto protoreflect.FileDescriptor

var file_engine_types_core_lango_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x5a, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x32, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x33, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x12, 0x5a, 0x10, 0x6d, 0x69, 0x6d, 0x69, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_engine_types_core_lango_proto_rawDescOnce sync.Once
	file_engine_types_core_lango_proto_rawDescData []byte
)

func file_engine_types_core_lango_proto_rawDescGZIP() []byte {
	file_engine_types_core_lango_proto_rawDescOnce.Do(func() {
		file_engine_types_core_lango_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_types_core_lango_proto_rawDesc), len(file_engine_types_core_lango_proto_rawDesc)))
	})
	return file_engine_types_core_lango_proto_rawDescData
}

var file_engine_types_core_lango_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engine_types_core_lango_proto_goTypes = []any{
	(*Lang)(nil), // 0: core.Lang
}
var file_engine_types_core_lango_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_engine_types_core_lango_proto_init() }
func file_engine_types_core_lango_proto_init() {
	if File_engine_types_core_lango_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_types_core_lango_proto_rawDesc), len(file_engine_types_core_lango_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_types_core_lango_proto_goTypes,
		DependencyIndexes: file_engine_types_core_lango_proto_depIdxs,
		MessageInfos:      file_engine_types_core_lango_proto_msgTypes,
	}.Build()
	File_engine_types_core_lango_proto = out.File
	file_engine_types_core_lango_proto_goTypes = nil
	file_engine_types_core_lango_proto_depIdxs = nil
}
